language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"

env:
  - INFLUX_VERSION=1.1.1 INFLUX_URL=https://dl.influxdata.com/influxdb/releases/influxdb_1.1.1_amd64.deb

before_install:
  - curl -L -O ${INFLUX_URL}
  - sudo dpkg -i influxdb_${INFLUX_VERSION}_amd64.deb
  - travis_retry sudo service influxdb restart
  - sudo service influxdb status

install: "pip install -r requirements.txt"

script: make test